[package]
name = "pistol"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "An implementation of a subset of the nmap scanning tool"
homepage = "https://github.com/rikonaka/pistol-rs"
documentation = "https://docs.rs/pistol"
repository = "https://github.com/rikonaka/pistol-rs"
readme = "README.md"
keywords = ["port-scan", "host-discovery", "penetration-test", "cybersecurity", "nmap"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1"
num_cpus = "^1"
rand = "^0"
subnetwork = "^0"
threadpool = "^1"
chrono = "^0"
gcdx = "^0"
crc32fast = "^1"
hex = "^0"
serde = { version="^1", features = ["derive"] }
serde_json = "^1"
pnet = { path = "./libpnet" }
pnet_datalink = { path = "./libpnet/pnet_datalink" }
pnet_macros_support = { path = "./libpnet/pnet_macros_support" }
pnet_macros = { path = "./libpnet/pnet_macros" }
pnet_packet = { path = "./libpnet/pnet_packet" }
# pnet = "^0"
# pnet_datalink = "^0"
# pnet_macros_support = "^0"
# pnet_macros = "^0"
# pnet_packet = "^0"
