[package]
name = "pistol"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
description = "Lets you customize network packages"
homepage = "https://github.com/rikonaka/pistol-rs"
documentation = "https://docs.rs/pistol"
repository = "https://github.com/rikonaka/pistol-rs"
readme = "README.md"
keywords = ["net", "scapy"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
