[package]
name = "pistol"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Lets you customize network packages"
homepage = "https://github.com/rikonaka/pistol-rs"
documentation = "https://docs.rs/pistol"
repository = "https://github.com/rikonaka/pistol-rs"
readme = "README.md"
keywords = ["net", "scapy"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "^0"
pnet_datalink = "^0"
rand = "0.8.5"
subnetwork = "^0"
tokio = { version = "^1", features = ["full"] }
